# Generated by Django 4.0 on 2021-12-20 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artsapp', '0002_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='total_score',
            field=models.FloatField(null=True),
        ),
    ]
