# Generated by Django 4.0 on 2022-01-01 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artsapp', '0005_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('rule', models.CharField(max_length=300)),
                ('type', models.CharField(max_length=300)),
                ('limitation_of_participation', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProgramRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='teacher',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='artsapp.group'),
        ),
        migrations.AlterField(
            model_name='group',
            name='total_score',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.FloatField()),
                ('rank', models.IntegerField(default=0)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='artsapp.group')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='result', to='artsapp.program')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='result', to='artsapp.programregistration')),
            ],
        ),
        migrations.AddField(
            model_name='programregistration',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_registration', to='artsapp.group'),
        ),
        migrations.AddField(
            model_name='programregistration',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_registration', to='artsapp.program'),
        ),
        migrations.AddField(
            model_name='programregistration',
            name='students',
            field=models.ManyToManyField(related_name='program_registration', to='artsapp.Student'),
        ),
    ]
